service: 
  name: notes-app-api
  publish: false # disable auto-publishing to the Serverless platform

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  accountId:  # found here https://console.aws.amazon.com/billing/home?#/account
  appSync:
    name: notes-appsync-api # defaults to api
    apiId: # only required for update-appsync/delete-appsync
    apiKey: # only required for update-appsync/delete-appsync
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-east-2 # required # region
      defaultAction: ALLOW # ALLOW
      userPoolId: us-east-2_KAskMPB4e # required # user pool ID
    mappingTemplatesLocation: mapping-templates # defaults to mapping-templates

    mappingTemplates:
      - dataSource: notes # data source name
        type: Query # Query, Mutation, Subscription
        field: getNote
        request: "getNote-request-mapping-template.txt" # request mapping template name
        response: "getNote-response-mapping-template.txt" # response mapping template name

    schema: schema.graphql # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"

    dataSources:
      - type: AMAZON_DYNAMODB
        name: notes # data source name
        description: 'Notes table' # DynamoDB Table Description
        config:
          tableName: 'notes' # DynamoDB Table Name
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/dynamo-${self:custom.appSync.serviceRole}"
