service: 
  name: ${file(../config.json):name}-s3
  publish: false # disable auto-publishing to the Serverless platform

plugins:
  - serverless-stack-output

custom:
  output:
    file: ../../${file(../config.json):name}-client/src/outputs/s3.json # toml, yaml, yml, and json format is available

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  deploymentBucket: ${file(../config.json):name}-${self:provider.stage}-serverless-deployment

# create the resources
resources:  # CloudFormation template syntax
  Resources:  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html

    # create assets bucket
    Bucket: # Logical ID (to reference resource in other parts of template)
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:service}-${self:provider.stage}-files
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"

  Outputs:
    Bucket:
      Value: 
        Ref : Bucket
    Region:
      Value:
        ${self:provider.region}