service: 
  name: ${file(../config.json):name}-dynamodb
  publish: false # disable auto-publishing to the Serverless platform

plugins:
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  deploymentBucket: ${file(../config.json):name}-${self:provider.stage}-serverless-deployment

custom:
  output:
    file: ../../${file(../config.json):name}-client/src/outputs/dynamodb.json # toml, yaml, yml, and json format is available

# create the resources
resources:  # CloudFormation template syntax
  Resources:  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
   
    # create DynamoDB table
    Table:  # Logical ID (to reference resource in other parts of template)
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:service}
        AttributeDefinitions: # describes key schema for table and indexes
          - AttributeName: id
            AttributeType: S  # 'S'tring, 'N'umeric, or 'B'oolean
        KeySchema:
          - AttributeName: id
            KeyType: HASH # partition key (RANGE for sort key)
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # create 'AppSyncDynamoDBServiceRole' to grant access to dynamodb table
    AppSyncDynamoDBServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "${self:service}-appsync-service-role"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "${self:service}-appsync-service-role-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - Fn::GetAtt: [ Table, Arn ]
                    - Fn::Join: ["", [ Fn::GetAtt: [ Table, Arn ], "/*" ]]

  Outputs:
    TableName:
      Value:
        Ref: Table
    AppSyncDynamoDBServiceRole:
      Value: 
        Ref: AppSyncDynamoDBServiceRole
